language: rust
rust:
  - stable
  - beta
  - nightly

# matrix:
#   allow_failures:
#     - rust: nightly

before_script:
  - rustup component add clippy-preview
  - cargo install cargo-kcov
  - cargo kcov --print-install-kcov-sh | sh

script:
  - cargo check --verbose
  - cargo test --verbose
  - cargo kcov --verbose --coveralls
  - cargo clippy
