[package]
name = "rusty-ports"
version = "0.1.0"
authors = ["Louis Brunner <louis.brunner.fr@gmail.com>"]

[dependencies]
clap = "2.25.0"
users = "0.7"
itertools = "0.7.3"
mockstream = "0.0.3"
ctrlc = { version = "3.0", features = ["termination"] }
